import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js",
    template: "%s | Mukunda Parajuli",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            height: "10rem",
          }}
        >
          <h1>Header</h1>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            height: "10rem",
          }}
        >
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
